### ISSUE TITLE
[US-5-6] Improve generator for Vuetify model

### ISSUE THREAD

**Issue by JuliaElizarova** [jdi-testing/jdi-qasp-ml#121]
Проблемы на данный момент:
- autocomplete не определяется вообще;
- combobox определяется как n/a или overflow-btn;
- путаются range-slider и slider;
- combobox, overflow-btn и autocomplete путаются между собой и часто определяются как n\a;
- text-field часто распознается как input.

Предложение по улучшению:
Добавить больше элементов классов, которые плохо расспознаются, сделать их более явными, разнообразить места их появления (например, autocomplete явно появляется только по одному разу на каждом из сгенерированных сайтов, сюда можно добавить какой-то элемент стохастики; а combobox, overflow-btn и autocomplete скорее всего всегда появляются рядом, если такая связка действительно есть, ее нужно попробовать как-то разбить)

**Comment by MariiaNebesnova** [comment]
решили: на сгенерированной странице выводить элементы в рандомном порядке и рандомном количестве (от 1 до 10)

**Comment by AlexeyGirin** [comment]
1. на сгенерированной странице выводить элементы в рандомном порядке и рандомном количестве (от 1 до 10)
2. Увеличить количество и разнообразие элементов combobox, overflow-btn и autocomplete по сравнению с другими элементами
3. Гарантировать, что combobox, overflow-btn и autocomplete не будут появляться рядом

**Comment by savinovava** [comment]
blocked by absence of specialists

**Comment by savinovava** [comment]
Перешли на рулы
