### ISSUE TITLE
[US-5-2] [NR-10] Add components to generator (available only from MUI 5.6)

### ISSUE THREAD

**Issue by suppnova** [jdi-testing/jdi-qasp-ml#34]
- [ ] MuiLoadingButton-root
- [ ] Buttons without children (< span >, < svg > ...)

- [ ] Update https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/35553284/Element+s+table

**Comment by savinovava** [comment]
Created: https://github.com/jdi-testing/jdn-ai/issues/468
